# <font color='blue'>MAI5002 - Fundamentos de Matemática Aplicada</font>

## <font color='blue'>Sistemas Lineares - Exercícios</font>

### Material produzido por Luis Gustavo Nonato
---
ICMC-USP

In [3]:
import numpy as np
import scipy.linalg as sl

### Exercício 1)

Escreva uma função em Python que receba uma matriz triangular inferior $\mathbf{L}$ e um vetor $\mathbf{b}$ e resolva o sistema $\mathbf{L}\mathbf{x}=\mathbf{b}$ por substituição direta. Compare o resultado de sua função com o obtido pelo método <font color='blue'> solve_triangular </font> do <font color='blue'> scipy </font>.

In [4]:
# Solucao

def substituicao_direta(L,b):
    x = np.zeros((b.shape[0],1))
    for i in range(b.shape[0]):
        x[i] = (b[i] - np.dot(L[i,:i],x[:i]))/L[i,i]
        
    return(x)

In [5]:
# construindo uma matriz triangular inferior
n = 10
T = np.tril(np.random.uniform(-1,1,size=(n,n))) #np.tril cria uma matriz triangular inferior

# construindo um vetor b
b = np.random.uniform(-1,1,size=(n,1))  #nx1

np.set_printoptions(precision=2)
print(T)
print('\n')
print(b.T)

[[ 0.86  0.    0.    0.    0.    0.    0.    0.    0.    0.  ]
 [-0.66  0.89  0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.92 -0.43  0.54  0.    0.    0.    0.    0.    0.    0.  ]
 [-0.83 -0.16 -0.17 -0.76  0.    0.    0.    0.    0.    0.  ]
 [ 0.07  0.86  0.25 -0.62  0.65  0.    0.    0.    0.    0.  ]
 [-0.46  0.85  0.41 -0.09 -0.08 -0.56  0.    0.    0.    0.  ]
 [-0.56  0.25 -0.06 -0.47 -0.66  0.66  0.42  0.    0.    0.  ]
 [ 0.7   0.73 -0.71 -0.11  0.15  0.59  0.35  0.3   0.    0.  ]
 [-0.7  -0.64 -0.18 -0.8  -0.46 -0.8   0.27 -0.3   0.4   0.  ]
 [-0.08 -0.84  0.78 -0.36 -0.19  0.32  0.81  0.67 -0.38 -0.09]]


[[-0.11 -0.19 -0.28 -0.25  0.92  0.15  0.9   1.   -0.79 -0.78]]


In [ ]:
# resolvendo o sistema e comparando com solve_triangular

x_meu = substituicao_direta(T,b)

#lower = True (Matriz triangular inferior) #unit_diagonal = False (diagonal de 1's falso)
x_scipy = sl.solve_triangular(T,b,lower=True,unit_diagonal=False,check_finite=False)

error = x_meu - x_scipy

print(np.max(error))
print('Mesma Solucao? ',np.allclose(error,np.zeros((n,n))))

### Exercício 2) 
Repita o exercício anterior, porém a função deve receber um matriz triangular superior e resolver o sistema por retrosubstituição.

In [6]:
# Solucao

def retrosubstituicao(U,b):
    x = np.zeros((b.shape[0],1))
    for i in range(b.shape[0]-1,-1,-1):
        x[i] = (b[i] - np.dot(U[i,i+1:],x[i+1:]))/U[i,i]
        
    return(x)


In [7]:
# construindo uma matriz triangular superior
n = 10
T = np.triu(np.random.uniform(-1,1,size=(n,n)))  #np.tril cria uma matriz triangular superior

# construindo um vetor b
b = np.random.uniform(-1,1,size=(n,1))

np.set_printoptions(precision=2)
print(T)
print('\n')
print(b.T)

[[ 0.6   0.82 -0.48 -0.31 -0.52 -0.4  -0.53 -0.32  0.61 -0.19]
 [ 0.   -0.61 -0.94  0.36  0.02 -0.12  0.68  0.28 -0.95  0.93]
 [ 0.    0.   -0.69  0.95 -0.17  0.86  0.73  0.14  0.08  0.13]
 [ 0.    0.    0.   -0.41  0.75 -0.52  0.53 -0.36  0.34  0.97]
 [ 0.    0.    0.    0.   -0.56 -0.81 -0.57  0.4   0.74  0.24]
 [ 0.    0.    0.    0.    0.    0.07  0.48 -0.55 -0.39 -0.22]
 [ 0.    0.    0.    0.    0.    0.    0.57 -0.77  0.24  0.42]
 [ 0.    0.    0.    0.    0.    0.    0.   -0.14  0.7  -0.52]
 [ 0.    0.    0.    0.    0.    0.    0.    0.   -0.42  0.08]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.01]]


[[ 0.04 -0.58  0.86  0.89 -0.91  0.85 -0.75  0.78  0.09  0.22]]


In [8]:
# resolvendo o sistema e comparando com solve_triangular

x_meu = retrosubstituicao(T,b)

#lower = False (Matriz triangular Superior) #unit_diagonal = False (diagonal de 1's falso)
x_scipy = sl.solve_triangular(T,b,lower=False,unit_diagonal=False,check_finite=False)

error = x_meu - x_scipy

print(np.max(error))
print('Mesma Solucao? ',np.allclose(error,np.zeros((n,n))))

9.094947017729282e-13
Mesma Solucao?  True


### Exercício 3)
Implemente o método de Gauss-Seidel como descrito em aula e verifique a corretude de seu método.

In [9]:
# Solução
def Gauss_Seidel(A,b):
    E = np.tril(A) #E é uma matriz triangular inferior gerada de A.
    E = np.linalg.inv(E) # calculando E^{-1}
    x = np.ones((A.shape[0],1))     #chute inicial
    r = b-np.dot(A,x)               #residuo inicial
    tol = 1e-10                     #tolerância
    maxiter = 1000                  #numero max de iterações
    i=0
    while ((np.max(np.abs(r))>tol) and (i < maxiter)):
        x = x + np.dot(E,r)
        r = b-np.dot(A,x)
        i = i+1
        
    if i < maxiter:
        print('Convergencia em ',i,' iteracoes')
        return(x)
    else:
        print('Nao convergiu')
        return(None)
    

In [10]:
# Construindo uma matrix diagonal dominante

n=10
eps = 1.0e-5
A = np.random.uniform(-1,1,size=(n,n))
d = np.sum(np.abs(A),axis=1)+eps
np.fill_diagonal(A,d)

# Construindo vetor b

b = np.random.uniform(-1,1,size=(n,1))

x = Gauss_Seidel(A,b)

# verificando a corretude da solução
x_np = np.linalg.solve(A,b)
error = x-x_np
print('Solucao está correta? ',np.allclose(error,np.zeros((n,1))))

Convergencia em  14  iteracoes
Solucao está correta?  True


### Exercício 4)
Um dos problemas com o método de Gauss-Seidel como descrito em aula é que a matriz $\mathbf{E}$ precisa ser invertida, o que torna-se inviável quando a matriz original é grande. Além disso, a inversão de $\mathbf{E}$ gera uma matriz triangular inferior cheia.

Uma outra forma de definir o método de Gauss-Seidel é através da fórmula:

$$
x_i^{k+1}=\frac{1}{a_{ii}}\left[b_i-\sum_{j<i}a_{ij}x_j^{k+1}-\sum_{j>i}a_{ij}x_j^{k}\right], \quad i=1,\ldots,n
$$

onde $x_i^{k}$ é a componente $i$ do vetor solução no passo $k$. A fórmula acima evita a inversão da matriz $\mathbf{E}$.

Implemente o método de Gauss-Seidel utilizando a fórmula acima e verifique a corretude da solução encontrada.

In [11]:
def Gauss_Seidel_v2(A,b):
    n = A.shape[0]
    x = np.ones((n,1))
    xn = np.zeros((n,1))
    r = b-np.dot(A,x)
    tol = 1e-10
    maxiter = 10000
    j=0
    while ((np.max(np.abs(r))>tol) and (j<maxiter)):
        x = np.copy(xn)
        for i in range(n):
            xn[i] = np.dot(A[i,:i],xn[:i,0])+np.dot(A[i,i+1:],x[i+1:,0])
            xn[i] = (b[i]-xn[i])/A[i,i]
        r = b-np.dot(A,xn)
        j = j+1
          
    if j < maxiter:
        print('Convergencia em ',j,' iteracoes')
        return(x)
    else:
        print('Nao convergiu')
        return(None)
    

In [12]:
# Construindo uma matrix diagonal dominante

n=10
eps = 1.0e-5
A = np.random.uniform(-1,1,size=(n,n))
d = np.sum(np.abs(A),axis=1)+eps
np.fill_diagonal(A,d)

# Construindo vetor b

b = np.random.uniform(-1,1,size=(n,1))

x = Gauss_Seidel_v2(A,b)

# verificando a corretude da solução
x_np = np.linalg.solve(A,b)
error = x-x_np
print('Solucao está correta? ',np.allclose(error,np.zeros((n,1))))

Convergencia em  13  iteracoes
Solucao está correta?  True


### Exercício 5)
Faça uma comparação, em termos do número de iterações, entre os métodos de Jacobi, Gauss-Seidel e Gradiente Conjugado.

In [13]:
def Jacobi(A,b):
    D = np.diag(1/np.diag(A)) # matrix D^{-1} 
                              # (lembre-se que a inversa de uma matrix diagonal é uma 
                              # matrix diagonal com elementos 1/a_ii)
    x = np.ones((A.shape[0],1))
    r = b-np.dot(A,x)
    tol = 1e-10
    maxiter = 1000
    i=0
    while ((np.max(np.abs(r))>tol) and (i < maxiter)):
        x = x + np.dot(D,r)
        r = b-np.dot(A,x)
        i = i+1
        
    if i < maxiter:
        print('Convergencia em ',i,' iteracoes')
        return(x)
    else:
        print('Nao convergiu')
        return(None)

In [14]:
def gradiente_conjugado(A,b):
    x = np.ones((A.shape[0],1))
    r = b-np.dot(A,x)
    p = np.copy(r)
    tol = 1e-10
    i = 0
    while (np.max(np.abs(r))>tol): 
        s = np.dot(A,p)
        delta = np.dot(r.T,r)
        alpha = delta/np.dot(p.T,s)
        x = x+alpha*p
        r = r - alpha*s
        p = r + (np.dot(r.T,r))/(delta)*p
        i = i+1
      
    print('Convergiu em ',i,' iteracoes')
    return(x)

In [15]:
# constriundo uma matriz simétrica definida positiva
n = 100
X = np.random.uniform(-1,1,size=((n,n)))
Q,R = np.linalg.qr(X)
D = np.diag(np.random.uniform(0.1,2,n))
A = np.linalg.multi_dot([Q,D,Q.T])

# Construindo vetor b
b = np.random.uniform(-1,1,size=(n,1))

x = gradiente_conjugado(A,b)

x = Gauss_Seidel_v2(A,b)

x = Jacobi(A,b)

Convergiu em  39  iteracoes
Convergencia em  115  iteracoes
Convergencia em  222  iteracoes
