# <font color='blue'>MAI5002 - Fundamentos de Matemática Aplicada</font>

## <font color='blue'>Sistemas Lineares</font>

### Material produzido por Luis Gustavo Nonato
---
ICMC-USP

### Conteúdo
- Métodos Diretos
    - Decomposição LU
    - Cholesky
- Métodos Iterativos
    - Iteração de Ponto Fixo
        - Jacobi e Gauss–Seidel
    - Gradiente Conjugado

---

## <font color='blue'>Métodos Diretos</font>
###  <font color='blue'> Decomposição LU</font>

Considere uma matriz $\mathbf{A}$ $n\times n$ com posto completo

$$
\mathbf{A}=\begin{bmatrix}
a_{11} & a_{12} & a_{13}& \cdots & a_{1n}\\
a_{21} & a_{22} & a_{23}& \cdots & a_{2n}\\
a_{31} & a_{32} & a_{33}& \cdots & a_{3n}\\
       &        & &\vdots & \\
a_{n1} & a_{n2} & a_{n3}& \cdots & a_{nn}
\end{bmatrix}
$$

e a matriz $\mathbf{M}^{(1)}$ como definida abaixo:

$$
\mathbf{M}^{(1)} = \begin{bmatrix}
 1      & 0 & 0 & \cdots & 0\\
-l_{21} & 1 & 0 & \cdots & 0\\
-l_{31} & 0 & 1 & \cdots & 0\\
        &   &   & \vdots &  \\
-l_{n1} & 0 & 0 & \cdots & 1
\end{bmatrix}
\qquad \mbox{ onde }\quad l_{i1} = \frac{a_{i1}}{a_{11}}
$$
Multiplicando $\mathbf{M}^{(1)}$ pela matriz $\mathbf{A}$ obtemos uma nova matriz onde todos os elementos da primeira coluna abaixo da diagonal são iguais a zero:
$$
\mathbf{A}^{(1)}=\mathbf{M}^{(1)}\mathbf{A}=
\begin{bmatrix}
a_{11} & a_{12} & a_{13}& \cdots & a_{1n}\\
0 & a_{22}^{(1)} & a_{23}^{(1)} & \cdots & a_{2n}^{(1)}\\
0 & a_{32}^{(1)} & a_{33}^{(1)} & \cdots & a_{3n}^{(1)}\\
       &        & & \vdots & \\
0 & a_{n2}^{(1)} & a_{n3}^{(1)} & \cdots & a_{nn}^{(1)}
\end{bmatrix}
$$

O mesmo procedimento pode ser realizado para zerar os elementos da segunda coluna abaixo da diagonal.

$$
\mathbf{M}^{(2)} = \begin{bmatrix}
 1 & 0 & 0 & \cdots & 0\\
 0 & 1 & 0 & \cdots & 0\\
 0 & -l_{32} & 1 & \cdots & 0\\
   &   &   & \vdots &  \\
 0 & -l_{n2} & 0 & \cdots & 1
\end{bmatrix}
\qquad \mbox{ onde }\quad l_{i2} = \frac{a_{i2}^{(1)}}{a_{22}^{(1)}}\quad
\\ \\
\mathbf{A}^{(2)}=\mathbf{M}^{(2)}\mathbf{A}^{(1)}=\mathbf{M}^{(2)}\mathbf{M}^{(1)}\mathbf{A}
\begin{bmatrix}
a_{11} & a_{12} & a_{13}& \cdots & a_{1n}\\
0 & a_{22}^{(1)} & a_{23}^{(1)} & \cdots & a_{2n}^{(1)}\\
0 & 0 & a_{33}^{(2)} & \cdots & a_{3n}^{(2)}\\
       &        & & \vdots & \\
0 & 0 & a_{n3}^{(2)} & \cdots & a_{nn}^{(2)}
\end{bmatrix}
$$

O processo acima pode ser repetido $n-1$ vezes, resultando em

$$
\mathbf{U}=\mathbf{A}^{(n-1)}=\mathbf{M}^{(n-1)}\cdots\mathbf{M}^{(2)}\mathbf{M}^{(1)}\mathbf{A}
$$

$$
\mathbf{U}=\begin{bmatrix}
a_{11} & a_{12} & a_{13}& \cdots & a_{1n}\\
0 & a_{22}^{(1)} & a_{23}^{(1)} & \cdots & a_{2n}^{(1)}\\
0 & 0 & a_{33}^{(2)} & \cdots & a_{3n}^{(2)}\\
       &        & & \vdots & \\
0 & 0 & 0 & \cdots & a_{nn}^{(n-1)}
\end{bmatrix}\quad \mbox{(matriz triangular superior)}
$$

Uma propriedade interessante das matrizes $\mathbf{M}^{(i)}$ é 

$$[\mathbf{M}^{(i)}]^{-1} = (-1)\mathbf{M}^{(i)}$$ 

Por exemplo:

$$
\begin{bmatrix}
 1      & 0 & 0 & \cdots & 0\\
-l_{21} & 1 & 0 & \cdots & 0\\
-l_{31} & 0 & 1 & \cdots & 0\\
        &   &   & \vdots &  \\
-l_{n1} & 0 & 0 & \cdots & 1
\end{bmatrix}
\begin{bmatrix}
 1      & 0 & 0 & \cdots & 0\\
l_{21} & 1 & 0 & \cdots & 0\\
l_{31} & 0 & 1 & \cdots & 0\\
        &   &   & \vdots &  \\
l_{n1} & 0 & 0 & \cdots & 1
\end{bmatrix}=
\begin{bmatrix}
 1 & 0 & 0 & \cdots & 0\\
 0 & 1 & 0 & \cdots & 0\\
 0 & 0 & 1 & \cdots & 0\\
        &   &   & \vdots &  \\
 0 & 0 & 0 & \cdots & 1
 \end{bmatrix} \mbox{(matriz identidade)}
$$

Portanto 

$$
\mathbf{U}=\mathbf{M}^{(n-1)}\cdots\mathbf{M}^{(2)}\mathbf{M}^{(1)}\mathbf{A}\quad\Longrightarrow\quad
[\mathbf{M}^{(1)}]^{-1}[\mathbf{M}^{(2)}]^{-1}\cdots[\mathbf{M}^{(n-1)}]^{-1}\mathbf{U}=\mathbf{A}
$$

É fácil verificar que 

$$
\mathbf{L}=[\mathbf{M}^{(1)}]^{-1}[\mathbf{M}^{(2)}]^{-1}\cdots[\mathbf{M}^{(n-1)}]^{-1}=
\begin{bmatrix}
 1      & 0 & 0 & \cdots & 0\\
l_{21}  & 1 & 0 & \cdots & 0\\
l_{31}  & l_{32} & 1 & \cdots & 0\\
        &   &   & \vdots &  \\
l_{n1}  & l_{n2} & l_{nn-1} & \cdots & 1
\end{bmatrix} \mbox{(matriz triangular inferior)}
$$

Desta forma, temos que a matriz $\mathbf{A}$ pode ser escrita como o produto de uma matriz triangular inferior ($\mathbf{L}$) com uma matriz triangular superior ($\mathbf{U}$), ou seja:

$$
\mathbf{A}=\mathbf{L}\mathbf{U}\quad \mbox{(decomposição LU)}
$$

###  <font color='blue'> Decomposição LU para solução de sistemas</font>

Uma das vantagens de se utilizar a decomposição LU é que a solução de um sistema linear $\mathbf{A}\mathbf{x}=\mathbf{b}$ se torna bastante simples. 

$$
\mathbf{A}\mathbf{x}=\mathbf{b}\Longrightarrow \mathbf{LU}\mathbf{x}=\mathbf{b}
$$

Fazendo $\mathbf{U}\mathbf{x}=\mathbf{y}$, calculamos $\mathbf{y}$ por substituição direta $\mathbf{L}\mathbf{y}=\mathbf{b}$ e então calculamos $\mathbf{x}$ por retrosubstituição $\mathbf{U}\mathbf{x}=\mathbf{y}$.

**Substituição Direta**

$$
\mathbf{L}\mathbf{y}=\mathbf{b}\Longrightarrow 
\begin{bmatrix}
 1      & 0 & 0 & \cdots & 0\\
l_{21}  & 1 & 0 & \cdots & 0\\
l_{31}  & l_{32} & 1 & \cdots & 0\\
        &   &   & \vdots &  \\
l_{n1}  & l_{n2} & l_{nn-1} & \cdots & 1
\end{bmatrix}
\begin{bmatrix}
y_1 \\ y_2 \\ y_3 \\ \vdots \\ y_n
\end{bmatrix}=
\begin{bmatrix}
b_1 \\ b_2 \\ b_3 \\ \vdots \\ b_n
\end{bmatrix}\Longrightarrow 
\begin{matrix}
y_1 = b_1\\
y_2 = b_2 - l_{21}y_1\\ 
y_3 = b_3 - l_{31}y_1 - l_{32}y_2\\
\vdots
\end{matrix}
$$

**Retrosubstituição**

$$
\mathbf{U}\mathbf{x}=\mathbf{y}\Longrightarrow 
\begin{bmatrix}
a_{11} & a_{12} & a_{13}& \cdots & a_{1n}\\
0 & a_{22}^{(1)} & a_{23}^{(1)} & \cdots & a_{2n}^{(1)}\\
0 & 0 & a_{33}^{(2)} & \cdots & a_{3n}^{(2)}\\
       &        & & \vdots & \\
0 & 0 & 0 & \cdots & a_{nn}^{(n-1)}
\end{bmatrix}
\begin{bmatrix}
x_1 \\ x_2 \\ x_3 \\ \vdots \\ x_n
\end{bmatrix}
\begin{bmatrix}
y_1 \\ y_2 \\ y_3 \\ \vdots \\ y_n
\end{bmatrix}\Longrightarrow 
\begin{matrix}
\vdots\\
x_{n-1} = \frac{y_{n-1}-a_{n-1n}^{(n-2)}x_n}{a_{n-1n-1}^{(n-2)}}\\
x_n = \frac{y_n}{a_{nn}^{(n-1)}}
\end{matrix}
$$

###  <font color='blue'> Estratégia de Pivotamento</font>

A construção das matrizes $\mathbf{L}$ e $\mathbf{U}$ não pode ser realizada quando algum dos $a_{ii}^{(k)}=0$ (divisão por zero). Na verdade, quando $a_{ii}^{(k)}\approx 0$ erros numéricos acabam se acumulando, levando a decomposições inválidas. 

Este problema é contornado utilizando _pivotamento_ (troca de linhas). Por exemplo:

$$
\begin{bmatrix}
1 & 1 & 1 \\
1 & 1 & 2 \\
1 & 2 & 2 
\end{bmatrix}\Longrightarrow
\begin{bmatrix}
1 & 1 & 1 \\
0 & 0 & 1 \\
0 & 1 & 1 
\end{bmatrix}
$$

Porém, pode-se trocar a segunda e a a terceira linha, resultando em uma decomposição válida:

$$
\begin{bmatrix}
1 & 1 & 1 \\
1 & 2 & 2 \\
1 & 1 & 2 
\end{bmatrix}\Longrightarrow
\begin{bmatrix}
1 & 1 & 1 \\
0 & 1 & 1 \\
0 & 0 & 1 
\end{bmatrix}
$$

Pode-se mostrar que o processo de pivotamento resulta em uma decomposição da forma

$$
\mathbf{A}=\mathbf{P}^\top\mathbf{L}\mathbf{U}
$$

onde $\mathbf{P}$ é a matriz identidade com linhas permutadas. Como $\mathbf{P}$ é ortogonal, sua inversa é igual a sua transposta. Portanto, a solução de um sistema linear via decomposição LU com pivotamento é dado por:

$$
\mathbf{A}\mathbf{x}=\mathbf{b} \Longrightarrow \mathbf{P}^\top\mathbf{L}\mathbf{U}\mathbf{x}=\mathbf{b}
\Longrightarrow \mathbf{L}\mathbf{U}\mathbf{x}=\mathbf{P}\mathbf{b} 
$$

$$
\mathbf{L}\mathbf{y}=\mathbf{P}\mathbf{b}
$$

$$
\mathbf{U}\mathbf{x}=\mathbf{y}
$$

In [1]:
import numpy as np
import scipy.linalg as sl

n = 10
A = np.random.uniform(-1,1,size=(n,n))

P,L,U = sl.lu(A)   # Atenção: o scipy retorna a matriz transposta de P
np.set_printoptions(precision=2)
print(L)
print('\n')
print(U)
print('\n')
print(P)
print('\n')

Error = A - np.linalg.multi_dot([P,L,U])    # Verificando se a decomposição foi calculada corretamente
print(np.allclose(Error,np.zeros((n,n))))

[[ 1.    0.    0.    0.    0.    0.    0.    0.    0.    0.  ]
 [-0.63  1.    0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.79 -0.02  1.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.65 -0.52  1.    0.    0.    0.    0.    0.    0.  ]
 [-0.89  0.01  0.01 -0.73  1.    0.    0.    0.    0.    0.  ]
 [ 0.73  0.68 -0.12  0.59 -0.17  1.    0.    0.    0.    0.  ]
 [-0.55  0.99  0.12  0.47  0.4   0.28  1.    0.    0.    0.  ]
 [-0.36 -0.29 -0.22  0.04  0.53  0.94 -0.31  1.    0.    0.  ]
 [ 0.07  0.9   0.24  0.34 -0.54 -0.34  0.29 -0.65  1.    0.  ]
 [ 0.63  0.32 -0.15  0.99 -0.75 -0.43  0.41 -0.15 -0.94  1.  ]]


[[-0.96 -0.32 -0.91 -0.45  0.06 -0.08 -0.35  0.42 -0.69  0.82]
 [ 0.   -1.03 -0.1  -0.54 -0.22  0.56 -1.15 -0.23 -0.69  0.92]
 [ 0.    0.    1.24  0.89 -0.08 -0.69 -0.26 -0.83  0.16 -1.13]
 [ 0.    0.    0.    1.6   0.14  0.2   0.45 -1.13  0.51 -0.94]
 [ 0.    0.    0.    0.    1.14  0.96 -0.61  0.1   0.63  0.94]
 [ 0.    0.    0.    0.    0.   -1.    0.56  1.16  1

In [45]:
%%time
# Resolvendo um sistema linear via LU

n = 100
A = np.random.uniform(-1,1,size=(n,n))
b = np.random.uniform(-1,1,size=(n,1))

P,L,U = sl.lu(A)  # decoposição LU

# y = sl.solve_triangular(L,np.dot(P.T,b),lower=True,unit_diagonal=True,check_finite=False)
# x_LU = sl.solve_triangular(U,y,lower=False,unit_diagonal=False,check_finite=False)

CPU times: user 2.25 ms, sys: 1e+03 µs, total: 3.25 ms
Wall time: 1.74 ms


In [46]:
%%time
# solução dos sistemas triangulares

y = sl.solve_triangular(L,np.dot(P.T,b),lower=True,unit_diagonal=True,check_finite=False)
x_LU = sl.solve_triangular(U,y,lower=False,unit_diagonal=False,check_finite=False)

CPU times: user 337 µs, sys: 54 µs, total: 391 µs
Wall time: 350 µs


In [47]:
%%time
# Resolvendo o sistema diretamente com scipy

x_scipy = sl.solve(A,b)

CPU times: user 1.21 ms, sys: 870 µs, total: 2.08 ms
Wall time: 1.22 ms


In [48]:
%%time
# Resolvendo o sistema diretamente com numpy

x_numpy = np.linalg.solve(A,b)

CPU times: user 720 µs, sys: 2 µs, total: 722 µs
Wall time: 731 µs


In [49]:
print(np.allclose(x_LU-x_scipy,np.zeros((n,1))))
print(np.allclose(x_LU-x_numpy,np.zeros((n,1))))
print(np.allclose(x_scipy-x_numpy,np.zeros((n,1))))

0.0
True
True
True


###  <font color='blue'> Decomposição Cholesky</font>

Seja $\mathbf{A}$ uma matriz simétrica definida positiva. A decomposição Cholesky fatora a matriz $\mathbf{A}$ como um produto:

$$
\mathbf{A} = \mathbf{L}\mathbf{L}^\top
$$

onde $\mathbf{L}$ é uma matriz triangular inferior. Os elementos da matriz $\mathbf{L}$ podem ser calculados de forma direta. Vejamos um exemplo de uma matriz $3\times 3$.

$$
\begin{bmatrix}
a_{11} & a_{12} & a_{13} \\
a_{12} & a_{22} & a_{23}\\
a_{13} & a_{23} & a_{33}\\
\end{bmatrix} = 
\begin{bmatrix}
l_{11} & 0 & 0\\
l_{21} & l_{22} & 0\\
l_{31} & l_{32} & l_{33}\\
\end{bmatrix}
\begin{bmatrix}
l_{11} & l_{21} & l_{31}\\
0 & l_{22} & l_{32}\\
0 & 0 & l_{33}\\
\end{bmatrix}
$$

$$
\begin{matrix}
l_{11}=\sqrt{a_{11}} & l_{21}=\frac{a_{12}}{l_{11}} & l_{31}=\frac{a_{13}}{l_{11}}\\
l_{22}=\sqrt{a_{22}-l_{12}^2} & l_{32} = \frac{a_{23}-l_{31}l_{21}}{l_{22}} & \\
l_{33}=\sqrt{a_{33}-l_{31}^2-l_{32}^2}
\end{matrix}
$$

O fato da matriz $\mathbf{A}$ ser definida positiva garante que os elementos $l_{ii}$ são todos positivos.

In [56]:
import numpy as np

# constriundo uma matriz simétrica definida positiva
n = 10
X = np.random.uniform(-1,1,size=((n,n)))
Q,R = np.linalg.qr(X)
D = np.diag(np.random.uniform(0.1,2,n))

A = np.linalg.multi_dot([Q,D,Q.T])

L = np.linalg.cholesky(A)
np.set_printoptions(precision=2)
print(L)

Error = A - np.dot(L,L.T)    # Verificando se a decomposição foi calculada corretamente
print('\n')
print(np.allclose(Error,np.zeros((n,n))))

[[ 1.12  0.    0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.09  1.04  0.    0.    0.    0.    0.    0.    0.    0.  ]
 [-0.03  0.04  1.07  0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.26 -0.15 -0.01  0.94  0.    0.    0.    0.    0.    0.  ]
 [-0.16  0.12  0.06  0.09  0.89  0.    0.    0.    0.    0.  ]
 [-0.09 -0.08 -0.03  0.06 -0.19  1.18  0.    0.    0.    0.  ]
 [-0.19 -0.05 -0.19 -0.27 -0.28 -0.08  0.81  0.    0.    0.  ]
 [ 0.17  0.06 -0.09 -0.07  0.02  0.13  0.02  1.12  0.    0.  ]
 [-0.12  0.02  0.03  0.31 -0.23 -0.06  0.17 -0.03  0.84  0.  ]
 [-0.12  0.22  0.04  0.1  -0.35 -0.19 -0.19  0.18 -0.16  0.97]]


True


## <font color='blue'>Métodos Iterativos</font>

###  <font color='blue'> Iteração de Ponto Fixo</font>

Os métodos diretos possuem algumas características que podem torná-los inadequados para certos tipos de problemas, por exemplo:

- Se a matriz $\mathbf{A}$ é esparsa (possui muitos zeros), a decomposição LU irá gerar matrizes triangulares cheias. No caso da matriz $\mathbf{A}$ ser muito grande, a utilização de matrizes cheias pode inviabilizar a solução do sistema linear.

- Alguns tipos de problemas, como em mecânica dos fluidos, muitos sistemas lineares precisam ser resolvidos e a solução de um sistema pode ser muito parecida com a solução do próximo sistema a ser resolvido. Neste caso, é muito útil utilizar a solução anterior como ponto de partida para encontrar a próxima solução.

Nos casos acima, métodos iterativos podem ser empregados para se garantir uma maior eficiência computacional.

Métodos iterativos se baseiam na idéia de **iteração de ponto fixo**, que consiste em resolver o sistema empregando um esquema da forma:

$$
\mathbf{x}_{k+1} = \mathbf{g}(\mathbf{x}_k)
$$

Por exemplo, dado um sistema $\mathbf{A}\mathbf{x}=\mathbf{b}$, suponha que $\mathbf{A}$ possa ser escrita como a diferença entre duas matrizes, ou seja $\mathbf{A}=\mathbf{M}-\mathbf{N}$. Assim, o sistema se torna

$$
\mathbf{A}\mathbf{x}=\mathbf{b}\quad\Longrightarrow\quad (\mathbf{M}-\mathbf{N})\mathbf{x}=\mathbf{b}\quad\Longrightarrow\quad \mathbf{M}\mathbf{x} = \mathbf{N}\mathbf{x}+\mathbf{b}
$$

Supondo que $\mathbf{M}$ é inversível, podemos escrever o sistema iterativo

$$
\mathbf{x}_{k+1} = \mathbf{M}^{-1}\mathbf{N}\mathbf{x}_k + \mathbf{M}^{-1}\mathbf{b}\quad\Longrightarrow\quad \mathbf{x}_{k+1} = \mathbf{x}_k + \mathbf{M}^{-1}(\mathbf{b}-\mathbf{A}\mathbf{x}_k),\quad \mbox{pois}\quad \mathbf{N} = \mathbf{M} - \mathbf{A}
$$

Neste caso, $\mathbf{g}(\mathbf{x}_k)=\mathbf{x}_k + \mathbf{M}^{-1}(\mathbf{b}-\mathbf{A}\mathbf{x}_k)$

O processo iterativo começa com um "chute" inicial $\mathbf{x}_0$ e o erro introduzido neste primeiro passo é dado por $\mathbf{r}_0 = \mathbf{b}-\mathbf{A}\mathbf{x}_0$. Utilizando $\mathbf{x}_0$, podemos calcular $\mathbf{x}_1 = \mathbf{x}_0 + \mathbf{M}^{-1}\mathbf{r}_0$. Repetindo o processo, temos que:

$$
\mathbf{r}_k = \mathbf{b}-\mathbf{A}\mathbf{x}_k
$$
e
$$
\mathbf{x}_{k+1} = \mathbf{x}_k + \mathbf{M}^{-1}\mathbf{r}_k
$$

Existem duas questões importantes no processo iterativo descrito acima:

1. Como escolher a matriz $\mathbf{M}$
2. Garantir que o processo iterativo converge, isto é, guarantir que $\mathbf{r}_k\rightarrow \mathbf{0}$ quando $k\rightarrow\infty$

Diferentes escolhar de $\mathbf{M}$ levam a diferentes métodos iterativos e a garantia de convergência também está ligada a escolha da matriz $\mathbf{M}$.

####  <font color='blue'> Método de Jacobi</font>

Dado o sistema $\mathbf{A}\mathbf{x}=\mathbf{b}$, considere a matrix $\mathbf{M}=\mathbf{D}$ onde $\mathbf{D}$ é a matrix diagonal formada pelos elementos da diagonal de $\mathbf{A}$. Neste caso, o processo iterativo se torna:

$$
\mathbf{x}_{k+1} = \mathbf{x}_k + \mathbf{D}^{-1}\mathbf{r}_k
$$

####  <font color='blue'> Método de Gauss-Seidel</font>

Considere $\mathbf{M}=\mathbf{E}$, onde $\mathbf{E}$ é a matriz triangular inferior formada pela parte triangular inferior da matriz $\mathbf{A}$ (abaixo da diagonal de $\mathbf{A}$). Neste caso, o processo iterativo se torna:

$$
\mathbf{x}_{k+1} = \mathbf{x}_k + \mathbf{E}^{-1}\mathbf{r}_k
$$

####  <font color='blue'> Convergência do Processo Iterativo</font>

Temos que $\mathbf{r}_k = \mathbf{b}-\mathbf{A}\mathbf{x}_k$, assim podemos definir:

$$
\mathbf{e}_k = \mathbf{x} - \mathbf{x}_k = \mathbf{A}^{-1}\mathbf{r}_k
$$

O método será convergente se $\mathbf{e}_k\rightarrow\mathbf{0}$ quando $k\rightarrow\infty$. Sabemos que:

$$
\mathbf{x}_{k} = \mathbf{x}_{k-1} + \mathbf{M}^{-1}(\mathbf{b}-\mathbf{A}\mathbf{x}_{k-1}) = \mathbf{M}^{-1}\mathbf{b} + (\mathbf{I}-\mathbf{M}^{-1}\mathbf{A})\mathbf{x}_{k-1} \qquad \mbox{(1)}
$$

Se o método converge para a solução $\mathbf{x}$, teremos no final do processo:

$$
\mathbf{x}=\mathbf{M}^{-1}\mathbf{b} + (\mathbf{I}-\mathbf{M}^{-1}\mathbf{A})\mathbf{x}\qquad \mbox{(2)}
$$

Subtraindo a equação (2) da equação (1) e fazendo $\mathbf{T}=\mathbf{I}-\mathbf{M}^{-1}\mathbf{A}$, temos que

$$
\mathbf{e}_k = \mathbf{T}\mathbf{e}_{k-1}
$$

Aplicando a formula acima recursivamente encontramos que:

$$
\mathbf{e}_k = \mathbf{T}(\mathbf{T}\mathbf{e}_{k-2})=\cdots=\mathbf{T}^k\mathbf{e}_0 \qquad \mbox{(3)}
$$

----
**Pausa para o raio espectral de uma matriz**

Sejam $\lambda_1,\lambda_2,\ldots,\lambda_n$ os autovalores de uma matriz $\mathbf{A}$. O _raio espectral_ de $\mathbf{A}$ é definido como:

$$
\rho(\mathbf{A})=\max\{|\lambda_1|,|\lambda_2|,\ldots,|\lambda_n|\}
$$

Para qualquer norma $\|\mathbf{A}\|$ de uma uma matriz, temos que $\rho(\mathbf{A})\leq\|\mathbf{A}\|$.

----

**Teorema**: Dado um sistema linear $\mathbf{A}\mathbf{x}=\mathbf{b}$, um método iterativo da forma

$$
\mathbf{x}_{k+1}=\mathbf{x}_{k}+\mathbf{M}^{-1}\mathbf{r}_{k},\quad k=0,1,\ldots
$$

e a matriz de iteração $\mathbf{T}=\mathbf{I}-\mathbf{M}^{-1}\mathbf{A}$, o método iterativo é convergente se e somente se 

$$
\rho(\mathbf{T}) < 1
$$

Pode-se mostrar que se uma matriz $\mathbf{A}$ é estritamente diagonal dominante, isto é:

$$
|a_{ii}|>\sum_{j\neq i} |a_{ij}|, \quad \forall i
$$

então $\rho(\mathbf{T}) < 1$ nos métodos de Jacobi e Gauss-Seidel, ou seja:

$$
\rho(\mathbf{I}-\mathbf{D}^{-1}\mathbf{A}) < 1\quad \mbox{e}\quad \rho(\mathbf{I}-\mathbf{E}^{-1}\mathbf{A}) < 1
$$

In [60]:
import numpy as np

[[ 5.31 -0.55 -0.76 -0.31 -0.35 -0.81  0.65 -0.84  0.04  0.31]
 [ 0.61  4.99 -0.97  0.24  0.88 -0.19 -0.33  0.54 -0.22  0.78]
 [ 0.38  0.06  3.9   0.24  0.34  0.51 -0.34 -0.55 -0.92 -0.04]
 [-0.33  0.71 -0.3   4.21  0.43 -0.52 -0.91  0.09 -0.32  0.26]
 [ 0.38  0.04 -0.04  0.89  3.72 -0.31 -0.62  0.24 -0.12 -0.16]
 [-0.25 -0.98 -0.71  0.43  0.07  4.46 -0.35  0.43  0.34  0.48]
 [ 0.8  -0.7  -0.17 -0.38 -0.19  0.54  4.62 -0.29  0.84 -0.55]
 [-0.85  0.46  0.42 -0.02 -0.44 -0.08 -0.58  4.31  0.78  0.08]
 [ 0.3  -0.54 -0.01 -0.98  0.32 -0.23  0.29 -0.11  3.66  0.57]
 [-0.38  0.04  0.46 -0.07  0.52 -0.31  0.8   0.41  0.85  4.41]]


In [77]:
def Jacobi(A,b):
    D = np.diag(1/np.diag(A)) # matrix D^{-1} 
                              # (lembre-se que a inversa de uma matrix diagonal é uma 
                              # matrix diagonal com elementos 1/a_ii)
    x = np.ones((A.shape[0],1))
    r = b-np.dot(A,x)
    tol = 1e-10
    maxiter = 1000
    i=0
    while ((np.max(np.abs(r))>tol) and (i < maxiter)):
        x = x + np.dot(D,r)
        r = b-np.dot(A,x)
        i = i+1
        
    if i < maxiter:
        print('Convergencia em ',i,' iteracoes')
        return(x)
    else:
        print('Nao convergiu')
        return(None)

In [80]:
# Construindo uma matrix diagonal dominante

n=10
eps = 1.0e-5
A = np.random.uniform(-1,1,size=(n,n))
d = np.sum(np.abs(A),axis=1)+eps
np.fill_diagonal(A,d)

# Construindo vetor b

b = np.random.uniform(-1,1,size=(n,1))

x = Jacobi(A,b)

# verificando a corretude da solução
x_np = np.linalg.solve(A,b)
error = x-x_np
print('Solucao está correta? ',np.allclose(error,np.zeros((n,1))))

Convergencia em  26  iteracoes
Solucao está correta?  True


###  <font color='blue'> Gradiente Conjugado</font>

####  <font color='blue'> Gradiente Descendente</font>

Vamos considerar uma matrix $\mathbf{A}$ definida positiva e a função $\phi(\mathbf{x})$ dada por:

$$
\phi(\mathbf{x})=\frac{1}{2}\mathbf{x}^\top\mathbf{A}\mathbf{x}-\mathbf{b}^\top\mathbf{x}
$$

O gradiente de $\phi$ é dado por:

$$
\nabla\phi=\mathbf{A}\mathbf{x}-\mathbf{b}=-\mathbf{r}
$$

Como assumimos que $\mathbf{A}$ é definida positiva, o ponto de mínimo de $\phi$ é precisamente o ponto $\mathbf{x}$ onde $\nabla\phi=0$, seja, quando $\mathbf{A}\mathbf{x}=\mathbf{b}$. Assim, o ponto de mínimo de $\phi$ é a solução do sistema linear.

O ponto de mínimo de $\phi$ pode ser obtido utilizando a técnica de gradiente descendente:

$$
\mathbf{x}_{k+1}=\mathbf{x}_k+\alpha_k \mathbf{r}_k
$$

Neste contexto, gostariamos de, em cada passo da iteração, encontrar o valor de $\alpha_k$ tal que $\phi(\mathbf{x}_k+\alpha_k \mathbf{r}_k)$ seja o menor possível dentre todos os possíveis valores de $\alpha_k$. Em outras palavras, queremos minimizar 

$$
\frac{1}{2}\mathbf{\mathbf{x}_k+\alpha \mathbf{r}_k}^\top\mathbf{A}\mathbf{\mathbf{x}_k+\alpha \mathbf{r}_k}-\mathbf{b}^\top\mathbf{\mathbf{x}_k+\alpha \mathbf{r}_k} \quad\quad (4)
$$
com relação a $\alpha$. Derivando a equação (4) com relação a $\alpha$ e igualando a zero obtemos:

$$
\alpha\mathbf{r}_k^\top\mathbf{A}\mathbf{r}_k+\mathbf{r}_k^\top\mathbf{A}\mathbf{x}_k-\mathbf{r}_k^\top\mathbf{b}=0
$$

Como $\mathbf{A}\mathbf{x}_k-\mathbf{b}=-\mathbf{r}_k$, o valor de $\alpha_k$ que miniza $\phi(\mathbf{x}_k+\alpha_k \mathbf{r}_k)$ é dado por:

$$
\alpha_k = \frac{\mathbf{r}_k^\top\mathbf{r}_k}{\mathbf{r}_k^\top\mathbf{A}\mathbf{r}_k}
$$

In [6]:
import numpy as np

def linear_solve_grad_desc(A,b):
    x = np.ones((A.shape[0],1))
    r = b-np.dot(A,x)
    tol = 1e-10
    maxiter = 1000
    i=0
    while ((np.max(np.abs(r))>tol) and (i < maxiter)): 
        s = np.dot(A,r)
        alpha = np.dot(r.T,r)/np.dot(r.T,s)
        x = x+alpha*r
        r = b-np.dot(A,x)
        #r = r - alpha*s
        i=i+1
        
    if i < maxiter:
        print('Convergencia em ',i,' iteracoes')
        return(x)
    else:
        print('Nao convergiu')
        return(None)    

In [7]:
# constriundo uma matriz simétrica definida positiva
n = 100
X = np.random.uniform(-1,1,size=((n,n)))
Q,R = np.linalg.qr(X)
D = np.diag(np.random.uniform(0.1,2,n))
A = np.linalg.multi_dot([Q,D,Q.T])

# Construindo vetor b
b = np.random.uniform(-1,1,size=(n,1))

x = linear_solve_grad_desc(A,b)

# verificando a corretude da solução
x_np = np.linalg.solve(A,b)
error = x-x_np
print('Solucao está correta? ',np.allclose(error,np.zeros((n,1))))

Convergencia em  171  iteracoes
Solucao está correta?  True


Como a implementação acima mostra, o método de gradiente descendente demora a convergir.

A ideia do métodos de Grandientes Conjugados é utilizar uma direção de "descida" diferente da direção do gradiente. Pode-se mostrar que se a direção:

$$
\mathbf{p}_{k+1} = \mathbf{r}_{k+1}+\frac{\mathbf{r}_{k+1}^\top\mathbf{r}_{k+1}}{\mathbf{r}_{k}^\top\mathbf{r}_{k}}\mathbf{p}_{k},\quad \mathbf{p}_{0} = \mathbf{r}_{0}
$$
for escolhida, o processo iterativo encontra a solução em no máximo $n$ interações, onde $n$ é o número de linhas (ou colunas) da matriz $\mathbf{A}$. Neste caso, o tamanho do passo que minimiza a função $\phi$ é dado por:

$$
\alpha_k=\frac{\mathbf{r}_{k}^\top\mathbf{r}_{k}}{\mathbf{p}_{k}^\top\mathbf{A}\mathbf{p}_{k}}
$$

In [8]:
def gradiente_conjugado(A,b):
    x = np.ones((A.shape[0],1))
    r = b-np.dot(A,x)
    p = np.copy(r)
    tol = 1e-10
    i = 0
    while (np.max(np.abs(r))>tol): 
        s = np.dot(A,p)
        delta = np.dot(r.T,r)
        alpha = delta/np.dot(p.T,s)
        x = x+alpha*p
        r = r - alpha*s
        p = r + (np.dot(r.T,r))/(delta)*p
        i = i+1
      
    print('Convergiu em ',i,' iteracoes')
    return(x)

In [9]:
# constriundo uma matriz simétrica definida positiva
n = 100
X = np.random.uniform(-1,1,size=((n,n)))
Q,R = np.linalg.qr(X)
D = np.diag(np.random.uniform(0.1,2,n))
A = np.linalg.multi_dot([Q,D,Q.T])

# Construindo vetor b
b = np.random.uniform(-1,1,size=(n,1))

x = gradiente_conjugado(A,b)

# verificando a corretude da solução
x_np = np.linalg.solve(A,b)
error = x-x_np
print('Solucao está correta? ',np.allclose(error,np.zeros((n,1))))

Convergiu em  41  iteracoes
Solucao está correta?  True


In [135]:
import scipy.sparse.linalg as ssl

# constriundo uma matriz simétrica definida positiva
n = 10
X = np.random.uniform(-1,1,size=((n,n)))
Q,R = np.linalg.qr(X)
D = np.diag(np.random.uniform(0.1,2,n))
A = np.linalg.multi_dot([Q,D,Q.T])

# Construindo vetor b
b = np.random.uniform(-1,1,size=(n,1))

# Gradiente Conjugado do Scipy
x_sp,_ = ssl.cg(A,b)   # scipy retorna o vetor solucao e uma variável que indica se o método convergiu

# Nossa implementacao
x = gradiente_conjugado(A,b)

print(x.ravel())
print(x_sp.ravel())


Convergiu em  10  iteracoes
[-4.21 -0.86  5.02  0.87  1.25 -2.56  0.87  0.44 -0.39 -2.7 ]
[-4.21 -0.86  5.02  0.87  1.25 -2.56  0.87  0.44 -0.39 -2.7 ]


A generalização do método de gradiente conjugado para matrizes não simétricas é chamado de **gradiente bi-conjugado**.

In [136]:
# Constuindo uma matriz qualquer

n = 10
X = np.random.uniform(-1,1,size=((n,n)))

x_sp,_ = ssl.bicg(A,b)

x_np = np.linalg.solve(A,b)

print(x_sp.ravel())
print(x_np.ravel())

[-4.21 -0.86  5.02  0.87  1.25 -2.56  0.87  0.44 -0.39 -2.7 ]
[-4.21 -0.86  5.02  0.87  1.25 -2.56  0.87  0.44 -0.39 -2.7 ]
