# <font color='blue'>MAI5002 - Fundamentos de Matemática Aplicada</font>

## <font color='blue'>Sistemas Lineares - Solução dos Exercícios</font>

### Material produzido por Luis Gustavo Nonato
---
ICMC-USP

In [1]:
import numpy as np
import scipy.linalg as sl

### Exercício 1)

Escreva uma função em Python que receba uma matriz triangular inferior $\mathbf{L}$ e um vetor $\mathbf{b}$ e resolva o sistema $\mathbf{L}\mathbf{x}=\mathbf{b}$ por substituição direta. Compare o resultado de sua função com o obtido pelo método <font color='blue'> solve_triangular </font> do <font color='blue'> scipy </font>.

In [90]:
# Solucao

def substituicao_direta(L,b):
    x = np.zeros((b.shape[0],1))
    for i in range(b.shape[0]):
        x[i] = (b[i] - np.dot(L[i,:i],x[:i]))/L[i,i]
        
    return(x)

In [91]:
# construindo uma matriz triangular inferior
n = 10
T = np.tril(np.random.uniform(-1,1,size=(n,n)))

# construindo um vetor b
b = np.random.uniform(-1,1,size=(n,1))

np.set_printoptions(precision=2)
print(T)
print('\n')
print(b.T)

[[ 7.04e-01  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00
   0.00e+00  0.00e+00  0.00e+00]
 [ 9.41e-01  7.32e-01  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00
   0.00e+00  0.00e+00  0.00e+00]
 [-7.11e-01 -4.33e-01 -2.93e-01  0.00e+00  0.00e+00  0.00e+00  0.00e+00
   0.00e+00  0.00e+00  0.00e+00]
 [-3.13e-01 -2.06e-01  1.82e-01  9.02e-01  0.00e+00  0.00e+00  0.00e+00
   0.00e+00  0.00e+00  0.00e+00]
 [-6.39e-01 -3.24e-02  3.98e-03  1.56e-01 -2.69e-01  0.00e+00  0.00e+00
   0.00e+00  0.00e+00  0.00e+00]
 [-3.51e-01  4.59e-01 -9.45e-01 -8.81e-01  8.64e-01  6.27e-01  0.00e+00
   0.00e+00  0.00e+00  0.00e+00]
 [-4.97e-01 -3.65e-01 -1.41e-01  2.64e-02 -6.48e-01  1.29e-01 -7.01e-01
   0.00e+00  0.00e+00  0.00e+00]
 [-3.32e-01 -7.18e-01 -3.87e-01  8.38e-01 -5.64e-01  8.94e-01 -8.41e-01
  -1.04e-01  0.00e+00  0.00e+00]
 [ 1.44e-01 -1.28e-01 -7.68e-01 -2.47e-04 -9.93e-01  4.28e-01 -9.32e-01
   6.37e-01  5.71e-01  0.00e+00]
 [ 4.02e-01  9.64e-02 -3.28e-01  3.28e-01  4.61e-01  6.

In [92]:
# resolvendo o sistema e comparando com solve_triangular

x_meu = substituicao_direta(T,b)

x_scipy = sl.solve_triangular(T,b,lower=True,unit_diagonal=False,check_finite=False)

error = x_meu - x_scipy

print(np.max(error))
print('Mesma Solucao? ',np.allclose(error,np.zeros((n,n))))

2.1316282072803006e-14
Mesma Solucao?  True


### Exercício 2) 
Repita o exercício anterior, porém a função deve receber um matriz triangular superior e resolver o sistema por retrosubstituição.

In [96]:
# Solucao

def retrosubstituicao(U,b):
    x = np.zeros((b.shape[0],1))
    for i in range(b.shape[0]-1,-1,-1):
        x[i] = (b[i] - np.dot(U[i,i+1:],x[i+1:]))/U[i,i]
        
    return(x)

In [97]:
# construindo uma matriz triangular superior
n = 10
T = np.triu(np.random.uniform(-1,1,size=(n,n)))

# construindo um vetor b
b = np.random.uniform(-1,1,size=(n,1))

np.set_printoptions(precision=2)
print(T)
print('\n')
print(b.T)

[[ 0.03  0.65 -0.56 -0.67 -0.52  0.91  0.94  0.49  0.92  0.95]
 [ 0.    0.51 -0.75 -0.07  0.3   0.89  0.44  0.29 -0.59 -0.76]
 [ 0.    0.   -0.7  -0.38  0.42  0.16  0.35 -0.36 -0.02  0.11]
 [ 0.    0.    0.    0.99 -0.44  0.73 -0.66 -0.79  0.27 -0.84]
 [ 0.    0.    0.    0.   -0.84  0.1   0.06 -0.58  0.63  1.  ]
 [ 0.    0.    0.    0.    0.   -0.96  0.35 -0.58  0.17  0.44]
 [ 0.    0.    0.    0.    0.    0.   -0.3   0.76  0.97 -0.45]
 [ 0.    0.    0.    0.    0.    0.    0.    0.41 -0.68  0.17]
 [ 0.    0.    0.    0.    0.    0.    0.    0.   -0.66  0.1 ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.33]]


[[-0.78 -0.44  0.42  0.76 -0.77  0.31 -0.27 -0.1  -0.52  0.01]]


In [98]:
# resolvendo o sistema e comparando com solve_triangular

x_meu = retrosubstituicao(T,b)

x_scipy = sl.solve_triangular(T,b,lower=False,unit_diagonal=False,check_finite=False)

error = x_meu - x_scipy

print(np.max(error))
print('Mesma Solucao? ',np.allclose(error,np.zeros((n,n))))

1.4210854715202004e-14
Mesma Solucao?  True


### Exercício 3)
Implemente o método de Gauss-Seidel como descrito em aula e verifique a corretude de seu método.

In [56]:
def Gauss_Seidel(A,b):
    E = np.tril(A)       # tomando a parte triangular inferiro de A
    E = np.linalg.inv(E) # calculando E^{-1}
    x = np.ones((A.shape[0],1))
    r = b-np.dot(A,x)
    tol = 1e-10
    maxiter = 1000
    i=0
    while ((np.max(np.abs(r))>tol) and (i < maxiter)):
        x = x + np.dot(E,r)
        r = b-np.dot(A,x)
        i = i+1
        
    if i < maxiter:
        print('Convergencia em ',i,' iteracoes')
        return(x)
    else:
        print('Nao convergiu')
        return(None)

In [57]:
# Construindo uma matrix diagonal dominante

n=10
eps = 1.0e-5
A = np.random.uniform(-1,1,size=(n,n))
d = np.sum(np.abs(A),axis=1)+eps
np.fill_diagonal(A,d)

# Construindo vetor b

b = np.random.uniform(-1,1,size=(n,1))

x = Gauss_Seidel(A,b)

# verificando a corretude da solução
x_np = np.linalg.solve(A,b)
error = x-x_np
print('Solucao está correta? ',np.allclose(error,np.zeros((n,1))))

Convergencia em  17  iteracoes
Solucao está correta?  True


### Exercício 4)
Um dos problemas com o método de Gauss-Seidel como descrito em aula é que a matriz $\mathbf{E}$ precisa ser invertida, o que torna-se inviável quando a matriz original é grande. Além disso, a inversão de $\mathbf{E}$ gera uma matriz triangular inferior cheia.

Uma outra forma de definir o método de Gauss-Seidel é através da fórmula:

$$
x_i^{k+1}=\frac{1}{a_{ii}}\left[b_i-\sum_{j<i}a_{ij}x_j^{k+1}-\sum_{j>i}a_{ij}x_j^{k}\right], \quad i=1,\ldots,n
$$

onde $x_i^{k}$ é a componente $i$ do vetor solução no passo $k$. A fórmula acima evita a inversão da matriz $\mathbf{E}$.

Implemente o método de Gauss-Seidel utilizando a fórmula acima e verifique a corretude da solução encontrada.

In [84]:
def Gauss_Seidel_v2(A,b):
    n = A.shape[0]
    x = np.ones((n,1))
    xn = np.zeros((n,1))
    r = b-np.dot(A,x)
    tol = 1e-10
    maxiter = 10000
    j=0
    while ((np.max(np.abs(r))>tol) and (j<maxiter)):
        x = np.copy(xn)
        for i in range(n):
            xn[i] = np.dot(A[i,:i],xn[:i,0])+np.dot(A[i,i+1:],x[i+1:,0])
            xn[i] = (b[i]-xn[i])/A[i,i]
        r = b-np.dot(A,xn)
        j = j+1
          
    if j < maxiter:
        print('Convergencia em ',j,' iteracoes')
        return(x)
    else:
        print('Nao convergiu')
        return(None)

In [86]:
# Construindo uma matrix diagonal dominante

n=10
eps = 1.0e-5
A = np.random.uniform(-1,1,size=(n,n))
d = np.sum(np.abs(A),axis=1)+eps
np.fill_diagonal(A,d)

# Construindo vetor b

b = np.random.uniform(-1,1,size=(n,1))

x = Gauss_Seidel_v2(A,b)

# verificando a corretude da solução
x_np = np.linalg.solve(A,b)
error = x-x_np
print('Solucao está correta? ',np.allclose(error,np.zeros((n,1))))

Convergencia em  12  iteracoes
Solucao está correta?  True


### Exercício 5)
Faça uma comparação, em termos do número de iterações, entre os métodos de Jacobi, Gauss-Seidel e Gradiente Conjugado.