# <font color='blue'>MAI5002 - Fundamentos de Matemática Aplicada</font>

## <font color='blue'>Ortogonalidade</font>

### Material produzido por Luis Gustavo Nonato
---
ICMC-USP

### Conteúdo
- Subespaço Ortogonais
- Ortogonalidade dos Espaços Fundamentais
- Teorema Fundamental da Álgebra Linear
- Matrizes e o Mapeamento entre Espaços Fundamentais
- Base Ortogonal
- Gram-Schmidt e Fatoração QR

---

## <font color='blue'>Subespaços Ortogonais</font>

Considere dois vetores $\mathbf{u}$ and $\mathbf{v}$ em $\mathbb{R}^n$. Vamos sempre assumir que vetores correspondem a uma matriz com $n$ linhas e apenas uma coluna. Assim o produto escalar é dado pelo produto matricial

$$
<\mathbf{u},\mathbf{v}> = \mathbf{u}^\top\mathbf{v} = \mathbf{v}^\top\mathbf{u}
$$


Dois **vetores** $\mathbf{u}$ and $\mathbf{v}$ em $\mathbb{R}^n$ são **ortogonais** (perpendiculares) se:

$$
\mathbf{u}^\top\mathbf{v} = 0
$$

ou seja, se o produto escalar entre eles é zero. Se $\mathbf{u}^\top\mathbf{v}>0$ então o ângulo entre eles é menor que $90^o$ e se $\mathbf{u}^\top\mathbf{v}<0$ então o ângulo entre eles é maior que $90^o$.

**Ortogonalidade e Independência Linear**

Seja $\mathbf{u}_1,\ldots,\mathbf{u}_k$ um conjunto de vetores (não nulos) ortogonais, ou seja, $\mathbf{u}_i^\top\mathbf{u}_j = 0,\, \forall i\neq j$. Então, tal conjunto é LI.

## <font color='blue'>Ortogonalidade dos Espaços Fundamentais</font>
A idéia básica da ortogonalidade entre dois subespaços $\mathcal{S}_1$ e $\mathcal{S}_2$ é que para qualquer $\mathbf{u}\in\mathcal{S}_1$ e $\mathbf{v}\in\mathcal{S}_2$, então $\mathbf{u}^\top\mathbf{v} = 0$. 

Note que de acordo com o raciocínio acima, em $\mathbb{R}^3$, subespaços dados por duas retas ou por uma reta e um plano podem ser ortogonais, mas dois planos em $\mathbb{R}^3$ nunca serão ortogonais (consegue justificar este fato?).

**Ortogonalidade entre o Espaço da Linhas e o Espaço Nulo**

Considere uma matrix $\mathbf{A}$, $n\times k$ como descrita abaixo:

$$
\mathbf{A}=
\begin{bmatrix}
-\!- & \mathbf{a}^\top_1 & -\!-\\
& \vdots &\\
-\!- & \mathbf{a}^\top_n & -\!-
\end{bmatrix}
$$

Suponha que $\mathbf{x}$ é um vetor que pertença ao espaço nulo de $\mathbf{A}$, ou seja, $\mathbf{A}\mathbf{x}=\mathbf{0}$. Note que o produto de $\mathbf{A}$ por $\mathbf{x}$ resulta em um vetor onde cada entrada é o produto escalar entre uma linha de $\mathbf{A}$ e $\mathbf{x}$. Portanto:

$$
\mathbf{A}\mathbf{x}=
\begin{bmatrix}
-\!- & \mathbf{a}^\top_1 & -\!-\\
& \vdots &\\
-\!- & \mathbf{a}^\top_n & -\!-
\end{bmatrix}
\begin{bmatrix}
x_1 \\ x_2 \\ \cdots \\ x_k
\end{bmatrix}
=
\begin{bmatrix}
\mathbf{a}^\top_1\mathbf{x} \\ \mathbf{a}^\top_2\mathbf{x} \\ \cdots \\ \mathbf{a}^\top_n\mathbf{x}
\end{bmatrix}=
\begin{bmatrix}
0 \\ 0 \\ \cdots \\ 0
\end{bmatrix}
$$

Ou seja, se $\mathbf{x}$ é um vetor que pertence ao espaço nulo de $\mathbf{A}$ então todas as linhas de $\mathbf{A}$ são ortogonais a $\mathbf{x}$. Seja $\mathbf{v}$ um vetor no espaço linha de $\mathbf{A}$, então:

$$
\mathbf{v}=c_1\mathbf{a}_1+\cdots+\mathbf{a}_n\\
\downarrow\\
\mathbf{x}^\top\mathbf{v} = c_1\mathbf{x}^\top\mathbf{a}_1+\cdots+c_n\mathbf{x}^\top\mathbf{a}_n = 0
$$

Logo, **o espaço linha é ortogonal ao espaço nulo de uma matriz**.

#### Exemplo
Considere a matriz 
$$
\mathbf{A}=
\begin{bmatrix}
1 & 1 & 1\\
1 & 0 & 1
\end{bmatrix}
$$

Os vetores linha são LI (consegue justificar este fato?). Como o espaço linha $\mathcal{C}(\mathbf{A}^\top)$ é ortogonal ao espaço nulo $\mathcal{N}(\mathbf{A})$ e $dim(\mathcal{C}(\mathbf{A}^\top))+dim(\mathcal{N}(\mathbf{A}))=3$ (consequência do teorema do núcleo e da imagem), então o espaço nulo tem dimensão 1. 

Para encontrar um vetor que gera o espaço nulo basta encontrarmos um vetor $\mathbf{x}$ que seja ortogonal aos dois vetores linha. Neste caso, o vetor $[1,0,-1]$ satisfaz esta propriedade.

***Complemento ortogonal***

Dado um espaço vetorial $\mathcal{S}$, o espaço contendo dos os vetores que são ortogonais a $\mathcal{S}$, denotado $\mathcal{S}^\perp$,  é chamado **complemento ortogonal** de $\mathcal{S}$.

Dois subespaços podem ser orgonais sem que sejam complemento ortogonal um do outro. Por exemplo, em $\mathbb{R}^3$, o subespaço (reta) gerado pelo vetor $[1,0,0]$ e o subespaço gerado pelo vetor $[0,1,0]$ são ortogonais, porém não são subspaços complemento ortogonal um do outro (porque?). 

Para que dois espaços $\mathcal{S}_1$ e $\mathcal{S}_2$ em $\mathbb{R}^n$ sejam complemento ortogonal um do outro, devemos ter que:

1. $\mathcal{S}_1=\mathcal{S}_2^\perp$ e $\mathcal{S}_2=\mathcal{S}_1^\perp$
2. $dim(\mathcal{S}_1)+dim(\mathcal{S}_2)=n$

## <font color=blue> Teorema fundamental da Álgebra Linear</font>

Para qualquer matrix $\mathbf{A}$, temos que $\mathcal{C}(\mathbf{A}^\top)\subset\mathbb{R}^k$, $\mathcal{N}(\mathbf{A})\subset\mathbb{R}^k$ e $dim(\mathcal{C}(\mathbf{A}^\top))+dim(\mathcal{N}(\mathbf{A}))=k$, logo $\mathcal{N}(\mathbf{A})$ é o complemento orgotonal de $\mathcal{C}(\mathbf{A}^\top)$, ou seja, o espaço nulo é o complemento ortogonal do espaço linha.

O raciocínio acima pode ser aplicado à matriz $\mathbf{A}^\top$, o que nos permite concluir que o espaço coluna é o complemento ortogonal do espaço nulo à esquerda de $\mathbf{A}$. Portanto:

1. O espaço linha $\mathcal{C}(\mathbf{A}^\top)$ é o complemento ortogonal do espaço nulo $\mathcal{N}(\mathbf{A})$

2. O espaço coluna $\mathcal{C}(\mathbf{A})$ é o complemento ortogonal do espaço nulo à esquerda $\mathcal{N}(\mathbf{A^\top})$

<img src="tfal.png"  style="width: 400px;"/>

## <font color=blue>Matrizes e o Mapeamento entre Espaços Fundamentais</font>

Seja $\mathcal{U}$ um subespaço de $\mathbb{R}^n$ e $\mathcal{V}=\mathcal{U}^\perp$ o complemento ortogonal $\mathcal{U}$.  Suponha que $\mathbf{u}_1,\ldots,\mathbf{u}_k$ seja uma base para o espaço $\mathcal{U}$ e $\mathbf{v}_{k+1},\ldots,\mathbf{v}_n$ uma base para $\mathcal{V}$. Desta forma, o conjunto $\{\mathbf{u}_1,\ldots,\mathbf{u}_k,\mathbf{v}_{k+1},\ldots,\mathbf{v}_n\}$ forma uma base para $\mathbb{R}^n$, ou seja, qualquer vetor $\mathbf{x}\in\mathbb{R}^n$ pode ser escrito como:

$$
\mathbf{x}=(c_1\mathbf{u}_1+\cdots+c_k\mathbf{u}_k)+(c_{k+1}\mathbf{v}_{k+1}+\cdots+c_n\mathbf{v}_n)
$$

Ou seja, qualquer vetor em $\mathbb{R}^n$ é formado por uma parte $\mathbf{u}$ que está em $\mathcal{U}$ e outra parte $\mathbf{v}$ que está em $\mathcal{V}$, ou seja,

$$
\mathbf{x}=\mathbf{u}+\mathbf{v}
$$

Considere agora uma matriz $\mathbf{A}$ e suponha que $\mathcal{U}$ seja o espaço linha de $\mathbf{A}$ e $\mathcal{V}$ o espaço nulo de $\mathbf{A}$. Para qualquer vetor $\mathbf{x}$ o produto 

$$
\mathbf{A}\mathbf{x}=\mathbf{A}\mathbf{u}+\mathbf{A}\mathbf{v}
$$

onde $\mathbf{u}\in \mathcal{U}$ e $\mathbf{v}\in \mathcal{V}$. Porém, como $\mathbf{v}$ é um vetor no espaço nulo, temos que $\mathbf{A}\mathbf{v}=\mathbf{0}$, logo $\mathbf{A}\mathbf{x}=\mathbf{A}\mathbf{u}$. 

Lembrando que $\mathbf{u}$ é um vetor no espaço linha e que

$$
\mathbf{A}\mathbf{u}=
\begin{bmatrix}
| &  & |\\
\mathbf{a}_1  & \cdots & \mathbf{a}_k\\
| &  & |
\end{bmatrix}
\begin{bmatrix}
u_1 \\ \vdots \\ u_k
\end{bmatrix}=
u_1\mathbf{a}_1 + \cdots + u_k\mathbf{a}_k
$$

temos que $\mathbf{A}\mathbf{u}$ é um vetor no espaço coluna de $\mathbf{A}$. 

Portanto, temos que, data uma transformação linear $\mathbf{A}$, $n\times k$:

1. $\mathbf{A}$ mapeia seu espaço linha no seu espaço coluna
2. para qualquer vetor $\mathbf{x}\in\mathbb{R}^k$, parte de $\mathbf{x}$ é mapeado por $\mathbf{A}$ no espaço coluna e parte para a origem do espaço $\mathbb{R}^n$.

<img src="matrixmapping.png"  style="width: 400px;"/>

### Exercício Prático
Construa um exemplo mostrando que de fato uma transformação $\mathbf{A}$ mapeia o espaço das linhas no espaço coluna.

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [11]:
# Criando uma matrix A 3x3 onde apenas duas linhas são LI
A = np.zeros((3,3))
A[:2] = np.random.randint(0,10,size=(2,3))

# gerando uma linha linearmente dependente das outras
A[2] = 2*A[0]-A[1]
print(A)

[[ 1.  3.  8.]
 [ 1.  6.  2.]
 [ 1.  0. 14.]]


Apenas duas linhas de $\mathbf{A}$ sao LI, ou seja, o espaço linha é um subespaço com dimensão 2 (plano) no espaço $\mathbb{R}^3$. Vamos tomar as duas primeiras linhas de $\mathbf{A}$ como base para este espaço.

Como o espaço linha tem a mesma dimensão do espaço coluna, sabemos que o espaço coluna também tem dimensão 2, logo, apenas duas colunas de $\mathbf{A}$ são LI. Vamos tomar as duas primeiras colunas de $\mathbf{A}$ como base para este espaço.

O plano associado ao espaço linha é dado pela equação:
$$
\tilde{\mathbf{n}}=\tilde{\mathbf{a}}_1\times\tilde{\mathbf{a}}_2\\
\tilde{\mathbf{n}}^\top\mathbf{x}=0
$$
onde $\tilde{\mathbf{a}}_1$ e $\tilde{\mathbf{a}}_2$ são os vetores linha de $\mathbf{A}$ e $\mathbf{x}$ um vetor qualquer em $\mathbb{R}^3$.

In [12]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
%matplotlib qt 

# Visualizando o espaço linha

# gerando o plano associado ao espaço linha
normal_t = np.cross(A[0],A[1])
xx, yy = np.meshgrid(range(-3,3), range(-3,3))
zz = -(normal_t[0] * xx + normal_t[1] * yy)/normal_t[2]

# plot do plano
fig1 = plt.figure()
ax1 = fig1.add_subplot(111,projection='3d')
ax1.plot_surface(xx, yy, zz, alpha=0.2)
ax1.set_title('Espaco Linha')

# plot da origem
ax1.scatter(0,0,0,s=25,color='k')

# plot dos vetores base do plano
x1 = A[0]/np.linalg.norm(A[0])
x2 = A[1]/np.linalg.norm(A[1])
ax1.quiver(0, 0, 0, x1[0],x1[1],x1[2],color='blue')
ax1.quiver(0, 0, 0, x2[0],x2[1],x2[2],color='red')

# plot de uma combinação linear qualquer
a = 1
b = -1
y = a*x1+b*x2
ax1.quiver(0, 0, 0, y[0],y[1],y[2],color='green')

O plano associado ao espaço coluna é dado pela equação:
$$
{\mathbf{n}}={\mathbf{a}}_1\times{\mathbf{a}}_2\\
{\mathbf{n}}^\top\mathbf{x}=0
$$
onde ${\mathbf{a}}_1$ e ${\mathbf{a}}_2$ são os vetores coluna de $\mathbf{A}$ e $\mathbf{x}$ um vetor qualquer em $\mathbb{R}^3$.

In [13]:
# Visualizando o espaço coluna

# gerando o plano associado ao espaço coluna
normal = np.cross(A[:,0],A[:,1])
xx, yy = np.meshgrid(range(-3,3), range(-3,3))
zz = -(normal[0] * xx + normal[1] * yy)/normal[2]

# plot do plano
fig2 = plt.figure()
ax2 = fig2.add_subplot(111,projection='3d')
ax2.plot_surface(xx, yy, zz, alpha=0.2)
ax1.set_title('Espaco Coluna')

# plot da origem
ax2.scatter(0,0,0,s=25,color='k')

# plot dos vetores base do plano
x1 = A[:,0]/np.linalg.norm(A[:,0])
x2 = A[:,1]/np.linalg.norm(A[:,1])
ax2.quiver(0, 0, 0, x1[0],x1[1],x1[2],color='blue')
ax2.quiver(0, 0, 0, x2[0],x2[1],x2[2],color='red')

# plot de transformação do vetor y a partir do espaço linha no espaço coluna
x = np.dot(A,y)
ax2.quiver(0, 0, 0, x[0],x[1],x[2],color='orange')

## <font color='blue'> Base Ortogonal </font>

Uma **base ortogonal** para um (sub)espaço é uma base onde os vetores da base são ortogonais entre si. Se dividirmos cada vetor pela sua norma, os vetores se tornam de comprimento unitário e a base passa a ser chamada **base ortonormal**.

Matematicament, seja $\mathbf{u}_1,\ldots,\mathbf{u}_k$ uma base para um subespaço $\mathcal{S}\subset\mathbb{R}^n$. Tal base é ortonomal se 

$$
\mathbf{u}_i^\top\mathbf{u}_j =
\left\{\begin{matrix}
0 & \mbox{ se } i\neq j\\
1 & \mbox{ se } i = j
\end{matrix}\right.
$$

### Matriz Ortonormal (Ortogonal)
Seja $\mathbf{Q}$ uma matriz cujas colunas são ortonormais, então 

$$
\mathbf{Q}^\top\mathbf{Q}=
\begin{bmatrix}
-\!- & \mathbf{q}^\top_1 & -\!-\\
& \vdots &\\
-\!- & \mathbf{q}^\top_n & -\!-
\end{bmatrix}
\begin{bmatrix}
| &  & |\\
\mathbf{q}_1  & \cdots & \mathbf{q}_n\\
| &  & |
\end{bmatrix}=
\begin{bmatrix}
1 & 0 & \cdots & 0\\
0 & 1 & \cdots & 0\\
  &   & \vdots & \\
0 & 0 & \cdots & 1\\
\end{bmatrix}
$$

Se $\mathbf{Q}$ for uma matriz quadrada ela é chamada de **matriz ortonormal** e neste caso
$\mathbf{Q}^{-1}=\mathbf{Q}^\top$, ou seja, a inversa de uma matriz ortogonal é igual sua transposta.

Temos ainda que $\mathbf{Q}\mathbf{Q}^\top=\mathbf{I}$, logo **as linhas de uma matriz ortonormal também são ortonormais**.

#### Propriedades das matrizes ortonormais

**1. Preservação da norma por transformação ortonormal**

Uma matriz ortogonal corresponde a uma transformação linear que preserva o comprimento dos vetores no mapeamento. 

$$
\|\mathbf{Q}\mathbf{x}\|=\|\mathbf{x}\|\\
\downarrow\\
\|\mathbf{Q}\mathbf{x}\|^2= (\mathbf{Q}\mathbf{x})^\top(\mathbf{Q}\mathbf{x})= 
\mathbf{x}^\top\mathbf{Q}^\top\mathbf{Q}\mathbf{x} = \mathbf{x}^\top\mathbf{x}=
\|\mathbf{x}\|^2
$$

**2. Coeficientes da combinação linear de vetores ortonormais**

Se $\mathbf{q}_1,\ldots,\mathbf{q}_k$ é uma base ortonormal, então qualquer vetor $\mathbf{x}$ no espaço $\mathcal{S}$ gerado pela base é dado por

$$
\mathbf{x}=c_1\mathbf{q}_1+\cdots+c_k\mathbf{q}_k
$$

O fato importante é que como a base é ortogonal, os coeficientes $c_1,\ldots,c_k$ são obtidos a partir da projeção $\mathbf{x}$ nos vetores da base, ou seja:

$$
c_i=\mathbf{q}_i^\top\mathbf{x}
$$

Isto é verdade pois:

$$
\mathbf{x}=c_1\mathbf{q}_1+\cdots+c_k\mathbf{q}_k\\
\downarrow\\
\mathbf{q}_i^\top\mathbf{x}=\mathbf{q}_i^\top(c_1\mathbf{q}_1+\cdots+c_k\mathbf{q}_k)=c_i\mathbf{q}_i^\top\mathbf{q}_i = c_i
$$

## <font color='blue'> Gram-Schmidt e Fatoração QR</font>

O processo de Gram-Schmidt é um método ortogonalização de uma base, ou seja, dada uma base $\mathbf{u}_1,\ldots,\mathbf{u}_k$ para um espaço $\mathcal{S}$ o método de Gram-Schmidt constrói uma outra base $\mathbf{q}_1,\ldots,\mathbf{q}_k$  para o espaço  $\mathcal{S}$ que é ortonormal.

O processo funciona da seguinte forma:

$$
\mathbf{q}_1=\frac{\mathbf{u}_1}{\|\mathbf{u}_1\|}
$$

<img src="gram-schmidt2.png"  style="width: 300px;"/>

$$
\mathbf{\tilde{q}}_2 = \mathbf{u}_2 - (\mathbf{u}_2^\top\mathbf{q}_1)\mathbf{q}_1\\
\downarrow \\
\mathbf{q}_2 = \frac{\mathbf{\tilde{q}}_2}{\|\mathbf{\tilde{q}}_2\|}
$$

$$
\mathbf{\tilde{q}}_3 = \mathbf{u}_3 - (\mathbf{u}_3^\top\mathbf{q}_1)\mathbf{q}_1 - (\mathbf{u}_3^\top\mathbf{q}_2)\mathbf{q}_2\\
\downarrow \\
\mathbf{q}_3 = \frac{\mathbf{\tilde{q}}_3}{\|\mathbf{\tilde{q}}_3\|}
$$

No caso geral temos que:
$$
\mathbf{\tilde{q}}_i = \mathbf{u}_i - \sum_{j=1}^{i-1}(\mathbf{u}_i^\top\mathbf{q}_j)\mathbf{q}_j\\
\downarrow \\
\mathbf{q}_i = \frac{\mathbf{\tilde{q}}_i}{\|\mathbf{\tilde{q}}_i\|}
$$

In [14]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
%matplotlib qt 

# Exmplo de Gram-Schmidt im R3

# base em R3
u1 = np.array([1,1,1])
u1 = u1/np.linalg.norm(u1)   # a normalização só é necessária para a visualização

u2 = np.array([1,1,0])
u2 = u2/np.linalg.norm(u2)

u3 = np.array([0,0.5,1])
u3 = u3/np.linalg.norm(u3)

# base ortogonal por gram-schmidt
q1 = u1/np.linalg.norm(u1)

q2 = u2 - np.dot(u2.T,q1)*q1
q2 = q2/np.linalg.norm(q2)

q3 = u3 - np.dot(u3.T,q1)*q1 - np.dot(u3.T,q2)*q2
q3 = q3/np.linalg.norm(q3)

# plotando os vetores
fig1 = plt.figure()
ax1 = fig1.add_subplot(111,projection='3d')

# plot da origem
ax1.scatter(0,0,0,s=25,color='k')

c = 0.05
# plot dos vetores da base original
ax1.quiver(0, 0, 0, c*u1[0],c*u1[1],c*u1[2],color='blue')
ax1.quiver(0, 0, 0, c*u2[0],c*u2[1],c*u2[2],color='blue')
ax1.quiver(0, 0, 0, c*u3[0],c*u3[1],c*u3[2],color='blue')

d = 0.04
# plot dos vetores base ortonormal
ax1.quiver(0, 0, 0, d*q1[0],d*q1[1],d*q1[2],color='red')
ax1.quiver(0, 0, 0, d*q2[0],d*q2[1],d*q2[2],color='red')
ax1.quiver(0, 0, 0, d*q3[0],d*q3[1],d*q3[2],color='red')

### Fatoração QR

Considere a matriz abaixo, supondo que as colunas são LI:

$$
\mathbf{A}=
\begin{bmatrix}
| &  & |\\
\mathbf{u}_1  & \cdots & \mathbf{u}_k\\
| &  & |
\end{bmatrix}
$$

Aplicando o processo de ortogonalização de Gram-Schmidt, tempos que:

$$
\mathbf{q}_1=\frac{\mathbf{u}_1}{\|\mathbf{u}_1\|} \rightarrow \mathbf{u}_1=\mathbf{q}_1\|\mathbf{u}_1\|\\
\mathbf{q}_2=\frac{\mathbf{u}_2-(\mathbf{u}_2^\top\mathbf{q}_1)\mathbf{q}_1}{\|\mathbf{u}_2-(\mathbf{u}_2^\top\mathbf{q}_1)\mathbf{q}_1\|}\rightarrow \mathbf{u}_2=\mathbf{q}_2\|\mathbf{u}_2-(\mathbf{u}_2^\top\mathbf{q}_1)\mathbf{q}_1\| + (\mathbf{u}_2^\top\mathbf{q}_1)\mathbf{q}_1\\
\vdots\\
\mathbf{q}_i = \frac{\mathbf{u}_i-(\mathbf{u}_i^\top\mathbf{q}_1)\mathbf{q}_1-\cdots-(\mathbf{u}_i^\top\mathbf{q}_{i-1})\mathbf{q}_{i-1}}{\|\mathbf{u}_i-(\mathbf{u}_i^\top\mathbf{q}_1)\mathbf{q}_1-\cdots-(\mathbf{u}_i^\top\mathbf{q}_{i-1})\mathbf{q}_{i-1}\|}\rightarrow
\mathbf{u}_i = \mathbf{q}_i\|\mathbf{u}_i-\sum_{l=1}^{i-1}(\mathbf{u}_i^\top\mathbf{q}_l)\mathbf{q}_l\| + \sum_{l=1}^{i-1}(\mathbf{u}_i^\top\mathbf{q}_l)\mathbf{q}_l
$$

Se denotarmos:

$$
r_{ij}=\left\{\begin{array}{ll}
\mathbf{u}_i^\top\mathbf{q}_j & \mbox{ se } i\neq j\\
\|\mathbf{u}_i-\sum_{l=1}^{i-1}(\mathbf{u}_i^\top\mathbf{q}_l)\mathbf{q}_l\| & \mbox{ se } i=j
\end{array}\right.
$$

temos que:

$$
\mathbf{u}_i = \mathbf{q}_1 r_{1i} + \mathbf{q}_2 r_{2i} + \cdots + \mathbf{q}_i r_{ii}
$$

ou seja,

$$
\begin{bmatrix}
| &  & |\\
\mathbf{u}_1  & \cdots & \mathbf{u}_k\\
| &  & |
\end{bmatrix}=
\begin{bmatrix}
| &  & |\\
\mathbf{q}_1  & \cdots & \mathbf{q}_k\\
| &  & |
\end{bmatrix}
\begin{bmatrix}
r_{11} & r_{12} & \cdots & r_{1k}\\
0      & r_{22} & \cdots & r_{2k}\\
\vdots & \vdots & \ddots & \vdots\\
0      & 0      & \cdots & r_{kk}\\
\end{bmatrix}\\
\downarrow\\
\mathbf{U}=\mathbf{Q}\mathbf{R}
$$

onde $\mathbf{Q}$ é uma matriz ortogonal cujo espaço coluna é o mesmo que o espaço coluna de $\mathbf{U}$. Desta forma, o método QR é uma forma de calcular uma base ortonormal dado umm conjunto de vetores LI no espaço desejado.

In [22]:
A = np.random.randint(0,9,size=(3,3))
A[2] = A[0]+A[1]
print(A)

Q,R = np.linalg.qr(A)

print(Q)
print(R)

[[ 8  0  8]
 [ 0  4  2]
 [ 8  4 10]]
[[-0.70710678  0.40824829 -0.57735027]
 [-0.         -0.81649658 -0.57735027]
 [-0.70710678 -0.40824829  0.57735027]]
[[-1.13137085e+01 -2.82842712e+00 -1.27279221e+01]
 [ 0.00000000e+00 -4.89897949e+00 -2.44948974e+00]
 [ 0.00000000e+00  0.00000000e+00  6.66133815e-16]]
